//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  landing: Landing;
  landingConnection: LandingConnection;
  rooms: Rooms;
  roomsConnection: RoomsConnection;
  transcript: Transcript;
  transcriptConnection: TranscriptConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLandingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLandingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LandingFilter>;
};


export type QueryRoomsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRoomsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RoomsFilter>;
};


export type QueryTranscriptArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTranscriptConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TranscriptFilter>;
};

export type DocumentFilter = {
  landing?: InputMaybe<LandingFilter>;
  rooms?: InputMaybe<RoomsFilter>;
  transcript?: InputMaybe<TranscriptFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Landing | Rooms | Transcript | Folder;

export type LandingLedeAttribution = {
  __typename?: 'LandingLedeAttribution';
  prefix?: Maybe<Scalars['String']['output']>;
  linkText?: Maybe<Scalars['String']['output']>;
  linkUrl?: Maybe<Scalars['String']['output']>;
  suffix?: Maybe<Scalars['String']['output']>;
};

export type LandingPracticeGrid = {
  __typename?: 'LandingPracticeGrid';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type LandingFooterLinks = {
  __typename?: 'LandingFooterLinks';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Landing = Node & Document & {
  __typename?: 'Landing';
  mastheadKicker?: Maybe<Scalars['String']['output']>;
  mastheadLocation?: Maybe<Scalars['String']['output']>;
  mastheadMaintainedBy?: Maybe<Scalars['String']['output']>;
  mastheadMaintainerUrl?: Maybe<Scalars['String']['output']>;
  mastheadGithubUrl?: Maybe<Scalars['String']['output']>;
  mastheadEst?: Maybe<Scalars['String']['output']>;
  ledeAttribution?: Maybe<LandingLedeAttribution>;
  practiceGrid?: Maybe<Array<Maybe<LandingPracticeGrid>>>;
  footerSig?: Maybe<Scalars['String']['output']>;
  footerLinks?: Maybe<Array<Maybe<LandingFooterLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type LandingLedeAttributionFilter = {
  prefix?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
  linkUrl?: InputMaybe<StringFilter>;
  suffix?: InputMaybe<StringFilter>;
};

export type LandingPracticeGridFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type LandingFooterLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type LandingFilter = {
  mastheadKicker?: InputMaybe<StringFilter>;
  mastheadLocation?: InputMaybe<StringFilter>;
  mastheadMaintainedBy?: InputMaybe<StringFilter>;
  mastheadMaintainerUrl?: InputMaybe<StringFilter>;
  mastheadGithubUrl?: InputMaybe<StringFilter>;
  mastheadEst?: InputMaybe<StringFilter>;
  ledeAttribution?: InputMaybe<LandingLedeAttributionFilter>;
  practiceGrid?: InputMaybe<LandingPracticeGridFilter>;
  footerSig?: InputMaybe<StringFilter>;
  footerLinks?: InputMaybe<LandingFooterLinksFilter>;
};

export type LandingConnectionEdges = {
  __typename?: 'LandingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Landing>;
};

export type LandingConnection = Connection & {
  __typename?: 'LandingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LandingConnectionEdges>>>;
};

export type RoomsRosterSectionsMembers = {
  __typename?: 'RoomsRosterSectionsMembers';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
};

export type RoomsRosterSections = {
  __typename?: 'RoomsRosterSections';
  label?: Maybe<Scalars['String']['output']>;
  members?: Maybe<Array<Maybe<RoomsRosterSectionsMembers>>>;
};

export type Rooms = Node & Document & {
  __typename?: 'Rooms';
  order: Scalars['Float']['output'];
  index?: Maybe<Scalars['String']['output']>;
  titleMain: Scalars['String']['output'];
  titleSuffix?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
  metaLine1?: Maybe<Scalars['String']['output']>;
  metaLine2?: Maybe<Scalars['String']['output']>;
  githubUrl?: Maybe<Scalars['String']['output']>;
  anchor?: Maybe<Scalars['String']['output']>;
  rosterSections?: Maybe<Array<Maybe<RoomsRosterSections>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RoomsRosterSectionsMembersFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
};

export type RoomsRosterSectionsFilter = {
  label?: InputMaybe<StringFilter>;
  members?: InputMaybe<RoomsRosterSectionsMembersFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RoomsFilter = {
  order?: InputMaybe<NumberFilter>;
  index?: InputMaybe<StringFilter>;
  titleMain?: InputMaybe<StringFilter>;
  titleSuffix?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
  metaLine1?: InputMaybe<StringFilter>;
  metaLine2?: InputMaybe<StringFilter>;
  githubUrl?: InputMaybe<StringFilter>;
  anchor?: InputMaybe<StringFilter>;
  rosterSections?: InputMaybe<RoomsRosterSectionsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type RoomsConnectionEdges = {
  __typename?: 'RoomsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Rooms>;
};

export type RoomsConnection = Connection & {
  __typename?: 'RoomsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RoomsConnectionEdges>>>;
};

export type TranscriptEntries = {
  __typename?: 'TranscriptEntries';
  speaker?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type Transcript = Node & Document & {
  __typename?: 'Transcript';
  sectionTitle?: Maybe<Scalars['String']['output']>;
  sectionNote?: Maybe<Scalars['String']['output']>;
  headerLabel?: Maybe<Scalars['String']['output']>;
  source?: Maybe<Scalars['String']['output']>;
  prompt?: Maybe<Scalars['String']['output']>;
  entries?: Maybe<Array<Maybe<TranscriptEntries>>>;
  note?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TranscriptEntriesFilter = {
  speaker?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type TranscriptFilter = {
  sectionTitle?: InputMaybe<StringFilter>;
  sectionNote?: InputMaybe<StringFilter>;
  headerLabel?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
  prompt?: InputMaybe<StringFilter>;
  entries?: InputMaybe<TranscriptEntriesFilter>;
  note?: InputMaybe<StringFilter>;
};

export type TranscriptConnectionEdges = {
  __typename?: 'TranscriptConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Transcript>;
};

export type TranscriptConnection = Connection & {
  __typename?: 'TranscriptConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TranscriptConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateLanding: Landing;
  createLanding: Landing;
  updateRooms: Rooms;
  createRooms: Rooms;
  updateTranscript: Transcript;
  createTranscript: Transcript;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateLandingArgs = {
  relativePath: Scalars['String']['input'];
  params: LandingMutation;
};


export type MutationCreateLandingArgs = {
  relativePath: Scalars['String']['input'];
  params: LandingMutation;
};


export type MutationUpdateRoomsArgs = {
  relativePath: Scalars['String']['input'];
  params: RoomsMutation;
};


export type MutationCreateRoomsArgs = {
  relativePath: Scalars['String']['input'];
  params: RoomsMutation;
};


export type MutationUpdateTranscriptArgs = {
  relativePath: Scalars['String']['input'];
  params: TranscriptMutation;
};


export type MutationCreateTranscriptArgs = {
  relativePath: Scalars['String']['input'];
  params: TranscriptMutation;
};

export type DocumentUpdateMutation = {
  landing?: InputMaybe<LandingMutation>;
  rooms?: InputMaybe<RoomsMutation>;
  transcript?: InputMaybe<TranscriptMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  landing?: InputMaybe<LandingMutation>;
  rooms?: InputMaybe<RoomsMutation>;
  transcript?: InputMaybe<TranscriptMutation>;
};

export type LandingLedeAttributionMutation = {
  prefix?: InputMaybe<Scalars['String']['input']>;
  linkText?: InputMaybe<Scalars['String']['input']>;
  linkUrl?: InputMaybe<Scalars['String']['input']>;
  suffix?: InputMaybe<Scalars['String']['input']>;
};

export type LandingPracticeGridMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type LandingFooterLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type LandingMutation = {
  mastheadKicker?: InputMaybe<Scalars['String']['input']>;
  mastheadLocation?: InputMaybe<Scalars['String']['input']>;
  mastheadMaintainedBy?: InputMaybe<Scalars['String']['input']>;
  mastheadMaintainerUrl?: InputMaybe<Scalars['String']['input']>;
  mastheadGithubUrl?: InputMaybe<Scalars['String']['input']>;
  mastheadEst?: InputMaybe<Scalars['String']['input']>;
  ledeAttribution?: InputMaybe<LandingLedeAttributionMutation>;
  practiceGrid?: InputMaybe<Array<InputMaybe<LandingPracticeGridMutation>>>;
  footerSig?: InputMaybe<Scalars['String']['input']>;
  footerLinks?: InputMaybe<Array<InputMaybe<LandingFooterLinksMutation>>>;
};

export type RoomsRosterSectionsMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
};

export type RoomsRosterSectionsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  members?: InputMaybe<Array<InputMaybe<RoomsRosterSectionsMembersMutation>>>;
};

export type RoomsMutation = {
  order?: InputMaybe<Scalars['Float']['input']>;
  index?: InputMaybe<Scalars['String']['input']>;
  titleMain?: InputMaybe<Scalars['String']['input']>;
  titleSuffix?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
  metaLine1?: InputMaybe<Scalars['String']['input']>;
  metaLine2?: InputMaybe<Scalars['String']['input']>;
  githubUrl?: InputMaybe<Scalars['String']['input']>;
  anchor?: InputMaybe<Scalars['String']['input']>;
  rosterSections?: InputMaybe<Array<InputMaybe<RoomsRosterSectionsMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TranscriptEntriesMutation = {
  speaker?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type TranscriptMutation = {
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  sectionNote?: InputMaybe<Scalars['String']['input']>;
  headerLabel?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  prompt?: InputMaybe<Scalars['String']['input']>;
  entries?: InputMaybe<Array<InputMaybe<TranscriptEntriesMutation>>>;
  note?: InputMaybe<Scalars['String']['input']>;
};

export type LandingPartsFragment = { __typename: 'Landing', mastheadKicker?: string | null, mastheadLocation?: string | null, mastheadMaintainedBy?: string | null, mastheadMaintainerUrl?: string | null, mastheadGithubUrl?: string | null, mastheadEst?: string | null, footerSig?: string | null, ledeAttribution?: { __typename: 'LandingLedeAttribution', prefix?: string | null, linkText?: string | null, linkUrl?: string | null, suffix?: string | null } | null, practiceGrid?: Array<{ __typename: 'LandingPracticeGrid', heading?: string | null, body?: string | null } | null> | null, footerLinks?: Array<{ __typename: 'LandingFooterLinks', label?: string | null, url?: string | null } | null> | null };

export type RoomsPartsFragment = { __typename: 'Rooms', order: number, index?: string | null, titleMain: string, titleSuffix?: string | null, tag?: string | null, sub?: string | null, metaLine1?: string | null, metaLine2?: string | null, githubUrl?: string | null, anchor?: string | null, body?: any | null, rosterSections?: Array<{ __typename: 'RoomsRosterSections', label?: string | null, members?: Array<{ __typename: 'RoomsRosterSectionsMembers', name?: string | null, role?: string | null } | null> | null } | null> | null };

export type TranscriptPartsFragment = { __typename: 'Transcript', sectionTitle?: string | null, sectionNote?: string | null, headerLabel?: string | null, source?: string | null, prompt?: string | null, note?: string | null, entries?: Array<{ __typename: 'TranscriptEntries', speaker?: string | null, text?: string | null } | null> | null };

export type LandingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LandingQuery = { __typename?: 'Query', landing: { __typename: 'Landing', id: string, mastheadKicker?: string | null, mastheadLocation?: string | null, mastheadMaintainedBy?: string | null, mastheadMaintainerUrl?: string | null, mastheadGithubUrl?: string | null, mastheadEst?: string | null, footerSig?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, ledeAttribution?: { __typename: 'LandingLedeAttribution', prefix?: string | null, linkText?: string | null, linkUrl?: string | null, suffix?: string | null } | null, practiceGrid?: Array<{ __typename: 'LandingPracticeGrid', heading?: string | null, body?: string | null } | null> | null, footerLinks?: Array<{ __typename: 'LandingFooterLinks', label?: string | null, url?: string | null } | null> | null } };

export type LandingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LandingFilter>;
}>;


export type LandingConnectionQuery = { __typename?: 'Query', landingConnection: { __typename?: 'LandingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LandingConnectionEdges', cursor: string, node?: { __typename: 'Landing', id: string, mastheadKicker?: string | null, mastheadLocation?: string | null, mastheadMaintainedBy?: string | null, mastheadMaintainerUrl?: string | null, mastheadGithubUrl?: string | null, mastheadEst?: string | null, footerSig?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, ledeAttribution?: { __typename: 'LandingLedeAttribution', prefix?: string | null, linkText?: string | null, linkUrl?: string | null, suffix?: string | null } | null, practiceGrid?: Array<{ __typename: 'LandingPracticeGrid', heading?: string | null, body?: string | null } | null> | null, footerLinks?: Array<{ __typename: 'LandingFooterLinks', label?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export type RoomsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RoomsQuery = { __typename?: 'Query', rooms: { __typename: 'Rooms', id: string, order: number, index?: string | null, titleMain: string, titleSuffix?: string | null, tag?: string | null, sub?: string | null, metaLine1?: string | null, metaLine2?: string | null, githubUrl?: string | null, anchor?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rosterSections?: Array<{ __typename: 'RoomsRosterSections', label?: string | null, members?: Array<{ __typename: 'RoomsRosterSectionsMembers', name?: string | null, role?: string | null } | null> | null } | null> | null } };

export type RoomsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RoomsFilter>;
}>;


export type RoomsConnectionQuery = { __typename?: 'Query', roomsConnection: { __typename?: 'RoomsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RoomsConnectionEdges', cursor: string, node?: { __typename: 'Rooms', id: string, order: number, index?: string | null, titleMain: string, titleSuffix?: string | null, tag?: string | null, sub?: string | null, metaLine1?: string | null, metaLine2?: string | null, githubUrl?: string | null, anchor?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rosterSections?: Array<{ __typename: 'RoomsRosterSections', label?: string | null, members?: Array<{ __typename: 'RoomsRosterSectionsMembers', name?: string | null, role?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type TranscriptQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TranscriptQuery = { __typename?: 'Query', transcript: { __typename: 'Transcript', id: string, sectionTitle?: string | null, sectionNote?: string | null, headerLabel?: string | null, source?: string | null, prompt?: string | null, note?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, entries?: Array<{ __typename: 'TranscriptEntries', speaker?: string | null, text?: string | null } | null> | null } };

export type TranscriptConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TranscriptFilter>;
}>;


export type TranscriptConnectionQuery = { __typename?: 'Query', transcriptConnection: { __typename?: 'TranscriptConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TranscriptConnectionEdges', cursor: string, node?: { __typename: 'Transcript', id: string, sectionTitle?: string | null, sectionNote?: string | null, headerLabel?: string | null, source?: string | null, prompt?: string | null, note?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, entries?: Array<{ __typename: 'TranscriptEntries', speaker?: string | null, text?: string | null } | null> | null } | null } | null> | null } };

export const LandingPartsFragmentDoc = gql`
    fragment LandingParts on Landing {
  __typename
  mastheadKicker
  mastheadLocation
  mastheadMaintainedBy
  mastheadMaintainerUrl
  mastheadGithubUrl
  mastheadEst
  ledeAttribution {
    __typename
    prefix
    linkText
    linkUrl
    suffix
  }
  practiceGrid {
    __typename
    heading
    body
  }
  footerSig
  footerLinks {
    __typename
    label
    url
  }
}
    `;
export const RoomsPartsFragmentDoc = gql`
    fragment RoomsParts on Rooms {
  __typename
  order
  index
  titleMain
  titleSuffix
  tag
  sub
  metaLine1
  metaLine2
  githubUrl
  anchor
  rosterSections {
    __typename
    label
    members {
      __typename
      name
      role
    }
  }
  body
}
    `;
export const TranscriptPartsFragmentDoc = gql`
    fragment TranscriptParts on Transcript {
  __typename
  sectionTitle
  sectionNote
  headerLabel
  source
  prompt
  entries {
    __typename
    speaker
    text
  }
  note
}
    `;
export const LandingDocument = gql`
    query landing($relativePath: String!) {
  landing(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LandingParts
  }
}
    ${LandingPartsFragmentDoc}`;
export const LandingConnectionDocument = gql`
    query landingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LandingFilter) {
  landingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LandingParts
      }
    }
  }
}
    ${LandingPartsFragmentDoc}`;
export const RoomsDocument = gql`
    query rooms($relativePath: String!) {
  rooms(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RoomsParts
  }
}
    ${RoomsPartsFragmentDoc}`;
export const RoomsConnectionDocument = gql`
    query roomsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RoomsFilter) {
  roomsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RoomsParts
      }
    }
  }
}
    ${RoomsPartsFragmentDoc}`;
export const TranscriptDocument = gql`
    query transcript($relativePath: String!) {
  transcript(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TranscriptParts
  }
}
    ${TranscriptPartsFragmentDoc}`;
export const TranscriptConnectionDocument = gql`
    query transcriptConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TranscriptFilter) {
  transcriptConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TranscriptParts
      }
    }
  }
}
    ${TranscriptPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      landing(variables: LandingQueryVariables, options?: C): Promise<{data: LandingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingQueryVariables, query: string}> {
        return requester<{data: LandingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingQueryVariables, query: string}, LandingQueryVariables>(LandingDocument, variables, options);
      },
    landingConnection(variables?: LandingConnectionQueryVariables, options?: C): Promise<{data: LandingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingConnectionQueryVariables, query: string}> {
        return requester<{data: LandingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LandingConnectionQueryVariables, query: string}, LandingConnectionQueryVariables>(LandingConnectionDocument, variables, options);
      },
    rooms(variables: RoomsQueryVariables, options?: C): Promise<{data: RoomsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RoomsQueryVariables, query: string}> {
        return requester<{data: RoomsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RoomsQueryVariables, query: string}, RoomsQueryVariables>(RoomsDocument, variables, options);
      },
    roomsConnection(variables?: RoomsConnectionQueryVariables, options?: C): Promise<{data: RoomsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RoomsConnectionQueryVariables, query: string}> {
        return requester<{data: RoomsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RoomsConnectionQueryVariables, query: string}, RoomsConnectionQueryVariables>(RoomsConnectionDocument, variables, options);
      },
    transcript(variables: TranscriptQueryVariables, options?: C): Promise<{data: TranscriptQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TranscriptQueryVariables, query: string}> {
        return requester<{data: TranscriptQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TranscriptQueryVariables, query: string}, TranscriptQueryVariables>(TranscriptDocument, variables, options);
      },
    transcriptConnection(variables?: TranscriptConnectionQueryVariables, options?: C): Promise<{data: TranscriptConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TranscriptConnectionQueryVariables, query: string}> {
        return requester<{data: TranscriptConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TranscriptConnectionQueryVariables, query: string}, TranscriptConnectionQueryVariables>(TranscriptConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  